services:
    logger:
        image: topicos_2:logger
        container_name: logger
        ports:
            - "5001:8000"
    ai-model:
        image: topicos_2:ai_model
        container_name: ai-model
        environment:
            - LOGGER_SERVICE_BASE_URL=http://logger:8000
            - SERVICE_NAME=prediction_service
        ports:
            - "5000:8000"
        depends_on:
            - logger
    users:
        image: topicos_2:users_service
        container_name: users
        environment:
            - LOGGER_SERVICE_BASE_URL=http://logger:8000
            - SERVICE_NAME=users_service
        ports:
            - "5002:8000"
        depends_on:
            - logger
    api-core:
        image: topicos_2:api_core_service
        container_name: api_core
        environment:
            - LOGGER_SERVICE_BASE_URL=http://logger:8000
            - USERS_SERVICE_BASE_URL=http://users:8000
            - AI_MODEL_SERVICE_BASE_URL=http://ai-model:8000
            - SERVICE_NAME=api_core_service
        ports:
            - "5003:8000"
        depends_on:
            - logger
            - ai-model
            - users
